### ISSUE TITLE
Permission system based on "on_reaction" feature

### ISSUE THREAD

**Issue by krzypecu** [krzypecu/DiscordPython-Bot#29]
**Describe the solution you'd like**
Handle users based on reaction the post under selected message ID. Give role permissions/unlock channels/add colors.

**Comment by Noverewana** [comment]
Made a command that creates a message. 
The user specifies the message content, the channel it is supposed to be sent on, the emojis to react with and roles corresponding to them. 
If a user reacts to that message with a specified emoji he will get the corresponding role and if he deletes his reaction the role also will be deleted.
