### ISSUE TITLE
System for handling incoming and outgoing messages inside the servers

### ISSUE THREAD

**Issue by MichalZak17** [krzypecu/DiscordPython-Bot#3]
**Description**
Handling incoming and outgoing messages inside servers is the literal basis for the functioning and existence of the bot. Said system requires a comprehensive interface for receiving, transmitting and sending messages or information among other components. Messages and information will be sent not only to other components of the system, but also to the users themselves as a possible response to a given operation.

It is also important to create technical documentation for the component so that other people working in the team while writing other components at the same time can easily use the class or method in question, depending on what form the component will have.

**Comment by Noverewana** [comment]
Done
